name: Enterprise CI/CD with devsecops
on: 
    push: 
        branches: 
            - qa
        paths: 
            - ".github/workflows/*"
            - "client/**"
            - "server/**"
    workflow_dispatch: 
jobs: 
    git-leaks-scan: 
        runs-on: ubuntu-latest 
        steps: 
            - name: checkout source code
              uses: actions/checkout@v4 
            
            - name: Install gitleaks
              uses: gitleaks/gitleaks-action@v3
            
            - name: Run git leaks and generating reports 
              run: | 
                gitleaks git --report-format json \
                    --report-path gitleaks-report.json \
                    --exit-code 0 
                
            - name: Uploading report as artifact 
              uses: actions/upload-artifact@v4 
              with: 
                name: git-leak-report
                path: |
                    gitleaks-report.json
                if-no-files-found: warn 

    checkov-scan-tf: 
        runs-on: ubuntu-latest
        needs: git-leaks-scan 
        steps: 
            - uses: actions/checkout@v4 
            - name: Installing python 
              uses: actions/setup-python@v5 
              with: 
                python-version: "3.11"
            
            - name: Install checkov 
              run: pip install checkov 
            
            - name: Run checkov terraform scan 
              run: | 
                checkov -d . \
                  -- framework terraform \
                  -- output json > checkov-terraform-report.json || true        # if the checkov tests fail still have to continue running the pipeline   
            
            - name: Uploading checkov report Artifacts 
              uses: actions/upload-artifact@v4 
              with: 
                name: checkov-terraform-report
                path: checkov-terraform-report.json 
                if-no-files-found: warn 


    checkov-scan-k8s: 
        runs-on: ubuntu-latest
        needs: git-leaks-scan 
        steps: 
            - uses: actions/checkout@v4 
            - name: Installing python 
              uses: actions/setup-python@v5 
              with: 
                python-version: "3.11"
            
            - name: Install checkov 
              run: pip install checkov 
            
            - name: Run checkov k8s scan 
              run: | 
                checkov -d . \
                  -- framework kubernetes \
                  -- output json > checkov-k8s-report.json || true        # if the checkov tests fail still have to continue running the pipeline   
            
            - name: Uploading checkov report Artifacts 
              uses: actions/upload-artifact@v4 
              with: 
                name: checkov-k8s-report
                path: checkov-k8s-report.json 
                if-no-files-found: warn

    checkov-scan-dockerfile: 
        runs-on: ubuntu-latest
        needs: git-leaks-scan 
        steps: 
            - uses: actions/checkout@v4 
            - name: Installing python 
              uses: actions/setup-python@v5 
              with: 
                python-version: "3.11"
            
            - name: Install checkov 
              run: pip install checkov 
            
            - name: Run checkov dockerfile scan 
              run: | 
                checkov -d . \
                  -- framework dockerfile \
                  -- output json > checkov-dockerfile-report.json || true        # if the checkov tests fail still have to continue running the pipeline   
            
            - name: Uploading checkov report Artifacts 
              uses: actions/upload-artifact@v4 
              with: 
                name: checkov-dockerfile-report
                path: checkov-dockerfile-report.json 
                if-no-files-found: warn



    client-trivy-fs: 
        runs-on: ubuntu-latest
        needs: git-leaks-scan 
        steps: 
            - uses: actions/checkout@v4 
            - name: installing trivy 
              uses: aquasecurity/trivy-action@v0.36.0

            - name: verify trivy installation
              run: | 
                trivy --version 
                which trivy 

        
            - name: trivy fs on client 
              run: | 
                trivy fs ./client --format json --output client-trivy-report.json --severity HIGH,CRITICAL --ignore-unfixed --exit-code 0 
                trivy fs ./client --format table --severity HIGH,CRITICAL --ignore-unfixed --exit-code 0 > client-trivy-table-report.txt

            - name: uploading reports as artifacts 
              uses: actions/upload-artifact@v4 
              with: 
                name: client-trivy-reports 
                path: | 
                   client-trivy-report.json
                   client-trivy-table-report.txt 
                if-no-files-found: warn 

    server-trivy-fs: 
        runs-on: ubuntu-latest 
        needs: git-leaks-scan 
        steps: 
            - uses: actions/checkout@v4 
            - name: Installing trivy scanner 
              uses: aquasecurity/trivy-action@v0.36.0
              with: 
                scan-type: 'fs'
                scan-ref: './server'
                ignore-unfixed: true
                format: 'json'
                output: 'trivy-server-fs-result.json'
                severity: 'HIGH,CRITICAL'
                exit-code: 0
            
            - name: Uploading server trivy fs report 
              uses: actions/upload-artifact@v4
              with: 
                name: trivy-server-report-json
                path: 'trivy-server-fs-result.json'
                if-no-files-found: warn 
            
                

                

            
