name: Clear Workflow History
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete older runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 4
